### ISSUE TITLE
How model run on ndc ?

### ISSUE THREAD

**Issue by Ibrokhimsadikov** [alofgran/Drug-Price-Prediction#1]
Hi @alofgran , Thank you for sharing your work, very comprehensive and well-done work. while going over your scripts, I was curious how you ran your regression, it was a bit unclear for me whether you trained your model by grouping ndc. I mean did you run separate regression for each ndc

**Comment by alofgran** [comment]
Hello! 

Thanks for looking through my work. Admittedly it could be a bit cleaner (in fact, I’m in the process of converting the notebooks to py files at the moment, building out pipelines, streamlining processes, etc.) but I’m glad you’ve found some value in it. 

You’re correct that the custom class groups by ndc then runs a regression for each one. 

Alex

**Comment by Ibrokhimsadikov** [comment]
Excellent, thank you for your clarification, just of out of my curiosity, Why for example you did not use Time series forecasting like Arima for example. Is it may be due to lack historical time frame?

Thank you for your opinion

**Comment by alofgran** [comment]
That’s a good question.  I definitely considered it.  There are a few reasons I didn’t go for it initially: 
1) my experience with time series was limited 
2) I lacked the time to learn and implement it before the project’s due date
3) After running the standard regression, results were satisfactory for the minimum viable product so a move to time series didn’t seem necessary. 

However, this time around, I realize some of those problems can be eliminated by using something like Facebook’s Prophet package, so I think time series will be an interesting (and frankly, a more intuitive) solution if it yields similar results. 

Alex

**Comment by Ibrokhimsadikov** [comment]
Amazing, Thank you for your prompt reply. I am working on similar project where I have to also forecast package price for ndcs, I will start with simple algorithms and then want to compare with Arima or Prophet as well. Thank you once again for your sincere opinions
